FROM jasonrivers/nagios

# required for slack nagios integration
# https://ifsight.slack.com/services/B26K8UE13#service_setup -- expand the Setup area
RUN apt-get install -y libwww-perl libcrypt-ssleay-perl
